zlib is required for pillow
Should address the following error in python 3.8+
```cmd
The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pillow
Failed to build pillow
ERROR: Could not build wheels for pillow, which is required to install pyproject.toml-based projects
```